title: <p align="center"> Kunal Sahu </p>
logo: /assets/img/kkk.jpeg

description:
  <p align="center">
  <a href="Docs/Kunal Sahu_10 yrs.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/kunalsahu44/">LinkedIn</a> |
  
  <br>   
  11 Yrs of experience on designing ,developing architecture and platform(Infra) for highly scalable cloudbased distributed System and Microservices applications using AWS, Open Source technology, JAVA andLinux, Docker, Kubernetes, DCOS.
  <br>
  </p>



theme: jekyll-theme-minimal